### ISSUE TITLE
Update to newer versions of Azure SDK for Go

### ISSUE THREAD

**Issue by divega** [paraglider-project/paraglider#139]
Just as an example, the networking module seems to be on version 4.3.0 on https://azure.github.io/azure-sdk/releases/latest/mgmt/go.html, but if my understanding is correct, we depend on 2.2.1 in https://github.com/paraglider-project/paraglider/blob/5fadca579523fb2d708ad180c982796abf4d8634/go.mod#L10. 

It seems the documentation for the package in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v4 is stale and tells you to install v2 :( 

We should strive to stay on fresh bits, especially to get the latest security fixes, but not sure if there is an ongoing process we can follow.

**Comment by smcclure20** [comment]
Will be resolved by #146

**Comment by smcclure20** [comment]
The above PR was stale enough that it was hard to merge with main. Reviving with #311
