### ISSUE TITLE
[IBM] Compatibility with BGP/ASN

### ISSUE THREAD

**Issue by Cohen-J-Omer** [paraglider-project/paraglider#169]
After Examining the [VPC Go SDK repo](https://pkg.go.dev/github.com/IBM/vpc-go-sdk@v0.41.0/vpcv1#VPNGatewayPrototypeVPNGatewayPolicyModePrototype) and the [github repo](https://github.com/IBM/vpc-go-sdk/blob/master/vpcv1/vpc_v1.go), I don't believe it's possible to attach `bgp_peering_ip_addresses` to an IBM VPN gateway, or retrieve the gateway's Autonomous System Number (ASN).
Can you please advise on a way for the IBM plugin to stay compatible with the Paraglider interface?
Thanks.

**Comment by divega** [comment]
Triage: @Cohen-J-Omer we believe you are working on this. If you aren't, please remove the milestone.

**Comment by Cohen-J-Omer** [comment]
@divega Indeed. The next IBM VPN PR should address this issue, by allowing BGP disabled VPN connections on IBM to connect to BGP enabled VPN connections on Azure. GCP is next.

**Comment by Cohen-J-Omer** [comment]
Issue resolved by [PR#334](https://github.com/paraglider-project/paraglider/pull/334).
