### ISSUE TITLE
[GCP] Firewall rule naming sensitivity

### ISSUE THREAD

**Issue by smcclure20** [paraglider-project/paraglider#258]
GCP seems to have changed their requirements for firewall rules to be even more strict on which characters are acceptable.

For the release, I made a quick fix which makes sure the CLI rules do not have any common characters that would cause problems. But we should discuss how to handle this more properly. The user will encounter errors if rule names have unacceptable characters, so we should maybe make that more apparent or error out earlier. Not sure yet, but just marking the issue for now.

**Comment by divega** [comment]
Triage: We don't think this will happen again. If it does, we will have to address but we can create a new issue for it.
