### ISSUE TITLE
Don't run integration tests on docs-only PRs

### ISSUE THREAD

**Issue by smcclure20** [paraglider-project/paraglider#259]
Per discussion with @seankimkdy, this is already true but filters on /docs. It would be nice to filter on file type so that changes to things like the CONTRIBUTING file do not trigger builds.

**Comment by seankimkdy** [comment]
Yea this is an issue where we need to identify which files are important for which action. But it can also become very brittle as we add new files and forget to update workflows accordingly.

In the meantime, is there a reason we need CONTRIBUTING.md or CODE-OF-CONDUCT.md? I'm wondering why those can't just directly live in our docs.

**Comment by divega** [comment]
I think contributing and code of conduct files are on root by convention. People and even tooling might expect to see them there, but in some cases they can be just stubs with links to the actual content under the documentation, especially contributing.

**Comment by divega** [comment]
Triage: @seankimkdy, we moved this to backlog. If you disagree, please move it to vnext.
