### ISSUE TITLE
[Azure] Alternative Resources Cleanup 

### ISSUE THREAD

**Issue by Cohen-J-Omer** [paraglider-project/paraglider#289]
Hey team,
I'm having a hard time debugging IBM-Azure VPN connectivity due to Azure's plugin cleanup policy. 
My team doesn't get privileges on the Azure subscription level, but rather each team gets ownership over an Azure resource group, hence creating/deleting resource groups isn't possible.
With that in mind, I can't terminate test resources efficiently, forced to delete resources one-by-one, in a specific order, waiting for child resources to delete before going forward with deleting their parent resource.

I'm not sure we can rely on future users/devs to:
- Have full privileges over the entire subscription of their Azure account (to allow resource group creation/deletion).
- Have a resource group for themselves. Test cleanup would delete other team member's resources.

I would appreciate if the Azure plugin could implement a cleanup function that strictly deletes Paraglider resources matching specified parameters, such as a namespace/region.

Thanks.

**Comment by seankimkdy** [comment]
Discussed in standup today that I'll work on putting up code for tearing down each resource individually in Azure without deleting the resource group. We'll continue to brainstorm what's a better way to handle this (if there are any)
