### ISSUE TITLE
[IBM] Flatten folder structure

### ISSUE THREAD

**Issue by seankimkdy** [paraglider-project/paraglider#318]
It seems like it's best if we flatten `pkg/ibm/` into one folder instead of having `sdk` and `server`. This stems from the Go reference (https://go.dev/ref/spec#Packages)

> An implementation may require that all source files for a package inhabit the same directory.

where implementation means "implementation of a Go toolchain" (https://forum.golangbridge.org/t/calling-go-functions-defined-in-same-package-but-different-folders/32023/2).

I looked into this because of some exporting idiosyncrasy I had with @praveingk (https://github.com/paraglider-project/paraglider/pull/294#discussion_r1605509410).
 
Thoughts @praveingk @Cohen-J-Omer?

**Comment by Cohen-J-Omer** [comment]
@seankimkdy I'm fine with the proposed change, and have no issue implementing it myself, but I would appreciate it if we could postpone it until after the VPN PR will be merged.

**Comment by seankimkdy** [comment]
Ofc definitely after your big PR. I presume your rebase is nasty as it is.

**Comment by Cohen-J-Omer** [comment]
@seankimkdy I'm closing this issue as I believe [PR#401](https://github.com/paraglider-project/paraglider/pull/401) solved it.
