### ISSUE TITLE
Enable GitHub actions access to packages

### ISSUE THREAD

**Issue by praveingk** [paraglider-project/paraglider#374]
Currently, GH actions fails to push image and the following settings would need to be enabled.

https://github.com/docker/build-push-action/issues/463#issuecomment-924995909

**Comment by smcclure20** [comment]
I think I just changed this setting. Let me know if it is resolved. Also, I noticed the package visibility is private for now. Let me know if/when I should change that to public.

**Comment by smcclure20** [comment]
@praveingk Is this resolved? If so, can you close it?

**Comment by praveingk** [comment]
Yes, This seems to be fixed, with release action being successfully executed.
