### ISSUE TITLE
[Azure] Add integration tests that cover more scenarios

### ISSUE THREAD

**Issue by nnomier** [paraglider-project/paraglider#38]
Examples:
1. Connection between 2 vms in the same network
2. Connection between 2 vms in different networks (different regions)
3. Add duplicate rules and validate they're not added 
4. Delete non existing rules
5. Create multiple networks, use GetUsedAddressSpaces and validate the output
6. Failure cases, for example:  invalid vm description

**Comment by divega** [comment]
Triage: Sarah to split and close.

**Comment by smcclure20** [comment]
Closing since I think we can create issues for each particular new integration test we need and a general "increase coverage" issue will always be true. And, the ones listed here in particular are mostly either resolved or not the most pressing issues.
