### ISSUE TITLE
Terminology cleanup

### ISSUE THREAD

**Issue by seankimkdy** [paraglider-project/paraglider#82]
There are lots of different terms of the same concepts. In general, the philosophy should be to use cloud specific terminology within the cloud plugin. For parts of the code that aren't specific to a cloud, we should use a general term (which may be the same as one cloud's term). It's perhaps worth documenting these as well in our README so users are aware as well.

Let's use this as a running list of the terms we should be conscious of.

- Range (GCP) vs Address Prefix (Azure)
- VPN Gateway (GCP) vs Virtual Network Gateway (Azure)

**Comment by divega** [comment]
Triage: We believe we are in a relatively good place already on this, so closing.
